openapi: "3.0.0"

info:
  title: "Stroke Prediction API"
  description: "An api that returns the probability of stroke"
  version: "1.0"

paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
